# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c8ade1702744746c21befa2fdfa2c1d75b0cadbbc408dd403cc3d9258cf6093046a11c096642ee21cc3482deb0a9d95f00e008e7eaf9e3470aef79ef6fd5257

test:
  secret_key_base: a628241395cc8ba79a387b6648a94a07096699641dab3de9f5467af436b4617aa1e65741ac2fd2da943a7c80e89fb09a2c4d91c402512d6bf2a318ad48f3958d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
